In [1]:
#1 Creation of arrays
import numpy as np

arr=np.array([1,2,3])
print("Array with rank 1: \n",arr)

#n-dimensional array
arr=np.array([[1,2,3],
              [4,5,6]])
print("Array with rank 2: \n",arr)
print("Array is of type: ", type(arr))
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)
print("Array stores elements of type: ", arr.dtype)

#Constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex') #{(m*n), value, datatype}
print ("\nAn array initialized with all 6s."
            "Array type is complex:\n", d)

#using tuple
arr=np.array((1,2,3))
print("Array created using tuple: \n",arr)

Array with rank 1: 
 [1 2 3]
Array with rank 2: 
 [[1 2 3]
 [4 5 6]]
Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32

An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]
Array created using tuple: 
 [1 2 3]


In [2]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
print("Initial Array: \n",arr)
sliced_arr=arr[:2, ::2]
print("Array with first 2 rows and alternate columns(0 and 2): \n",sliced_arr)
index_arr=arr[[1,1,0,2],
             [2,3,1,0]]
#doubt on this topic
print ("\nElements at indices (1, 3), " "(1, 2), (0, 1), (3, 0):\n", index_arr)

Initial Array: 
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
Array with first 2 rows and alternate columns(0 and 2): 
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [6.  0.  2.  2.6]


In [3]:
#mathematical operations
print ("Adding 1 to every element:", arr + 1)
print ("\nSum of all array elements: ", arr.sum())
print ("\nArray sum:\n", arr + arr) #binary operation

# boolean array indexing example
cond = arr > 0 # cond is a boolean array
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)

# maximum element of array
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",arr.max(axis = 1))
 
# minimum element of array
print ("Column-wise minimum elements:",arr.min(axis = 0))
 
# cumulative sum along each row
print ("Cumulative sum along each row:\n",arr.cumsum(axis = 1))

Adding 1 to every element: [[ 0.   3.   1.   5. ]
 [ 5.   0.5  7.   1. ]
 [ 3.6  1.   8.   9. ]
 [ 4.  -6.   5.   3. ]]

Sum of all array elements:  34.1

Array sum:
 [[ -2.    4.    0.    8. ]
 [  8.   -1.   12.    0. ]
 [  5.2   0.   14.   16. ]
 [  6.  -14.    8.    4. ]]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]
Largest element is: 8.0
Row-wise maximum elements: [4. 6. 8. 4.]
Column-wise minimum elements: [-1. -7.  0.  0.]
Cumulative sum along each row:
 [[-1.   1.   1.   5. ]
 [ 4.   3.5  9.5  9.5]
 [ 2.6  2.6  9.6 17.6]
 [ 3.  -4.   0.   2. ]]


In [4]:
#Constructing Datatype
x = np.array([1, 2])  
print("Integer Datatype: ")
print(x.dtype)   # guessed by Numpy      
x = np.array([1.0, 2.0]) 
print("\nFloat Datatype: ")
print(x.dtype)  # guessed by Numpy
 
# Forced Datatype
x = np.array([1, 2], dtype = np.int64)   
print("\nForcing a Datatype: ")
print(x.dtype)

Integer Datatype: 
int32

Float Datatype: 
float64

Forcing a Datatype: 
int64


In [5]:
# Python program to demonstrate 
# the use of data type object
# with structured array.
import numpy as np
 
dt = np.dtype([('name', np.unicode_, 16),
               ('grades', np.float64, (2,))])
 
# x is a structured array with names
# and marks of students.
# Data type of name of the student is 
# np.unicode_ and data type of marks is 
# np.float(64)
x = np.array([('Sarah', (8.0, 7.0)),
              ('John', (6.0, 7.0))], dtype=dt)
 
print(x[1])
 
print("Grades of John are: ", x[1]['grades'])
print("Names are: ", x['name'])

('John', [6., 7.])
Grades of John are:  [6. 7.]
Names are:  ['Sarah' 'John']
