In [17]:
#1 Creation of arrays
import numpy as np

arr=np.array([1,2,3])
print("Array with rank 1: \n",arr)

#n-dimensional array
arr=np.array([[1,2,3],
              [4,5,6]])
print("Array with rank 2: \n",arr)
print("Array is of type: ", type(arr))
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)
print("Array stores elements of type: ", arr.dtype)

#Constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex') #{(m*n), value, datatype}
print ("\nAn array initialized with all 6s."
            "Array type is complex:\n", d)

#using tuple
arr=np.array((1,2,3))
print("Array created using tuple: \n",arr)


Array with rank 1: 
 [1 2 3]
Array with rank 2: 
 [[1 2 3]
 [4 5 6]]
Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32

An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]
Array created using tuple: 
 [1 2 3]


In [8]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
print("Initial Array: \n",arr)
sliced_arr=arr[:2, ::2]
print("Array with first 2 rows and alternate columns(0 and 2): \n",sliced_arr)
index_arr=arr[[1,1,0,2],
             [2,3,1,0]]
#doubt on this topic
print ("\nElements at indices (1, 3), " "(1, 2), (0, 1), (3, 0):\n", index_arr)

Initial Array: 
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
Array with first 2 rows and alternate columns(0 and 2): 
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [6.  0.  2.  2.6]


In [20]:
#mathematical operations
print ("Adding 1 to every element:", arr + 1)
print ("\nSum of all array elements: ", arr.sum())
print ("\nArray sum:\n", arr + arr) #binary operation

# boolean array indexing example
cond = arr > 0 # cond is a boolean array
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)

# maximum element of array
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",arr.max(axis = 1))
 
# minimum element of array
print ("Column-wise minimum elements:",arr.min(axis = 0))
 
# cumulative sum along each row
print ("Cumulative sum along each row:\n",arr.cumsum(axis = 1))

Adding 1 to every element: [2 3 4]

Sum of all array elements:  6

Array sum:
 [2 4 6]

Elements greater than 0:
 [1 2 3]
Largest element is: 3


AxisError: axis 1 is out of bounds for array of dimension 1

In [11]:
#Constructing Datatype
x = np.array([1, 2])  
print("Integer Datatype: ")
print(x.dtype)   # guessed by Numpy      
x = np.array([1.0, 2.0]) 
print("\nFloat Datatype: ")
print(x.dtype)  # guessed by Numpy
 
# Forced Datatype
x = np.array([1, 2], dtype = np.int64)   
print("\nForcing a Datatype: ")
print(x.dtype)

Integer Datatype: 
int32

Float Datatype: 
float64

Forcing a Datatype: 
int64


In [21]:
# Python program to demonstrate 
# the use of data type object
# with structured array.
import numpy as np
 
dt = np.dtype([('name', np.unicode_, 16),
               ('grades', np.float64, (2,))])
 
# x is a structured array with names
# and marks of students.
# Data type of name of the student is 
# np.unicode_ and data type of marks is 
# np.float(64)
x = np.array([('Sarah', (8.0, 7.0)),
              ('John', (6.0, 7.0))], dtype=dt)
 
print(x[1])
 
print("Grades of John are: ", x[1]['grades'])
print("Names are: ", x['name'])


('John', [6., 7.])
Grades of John are:  [6. 7.]
Names are:  ['Sarah' 'John']


In [4]:
#Indexing using numpy
import numpy as np
#1
a=np.arange(10,1,-2)
print("\n A sequential array with a negative step: \n",a)
 
# Indexes are specified inside the np.array method.
newarr = a[np.array([3, 1, 2 ])]
print("\n Elements at these indices are:\n",newarr)

#2
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = x[np.array([1, 3, -3])] # Index values can be negative.
print("\n Elements are : \n",arr)


 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]

 Elements are : 
 [2 4 7]


In [8]:
#Slicing a slice object is of the form start:stop:step
import numpy as np
 
a = np.arange(20) # Arrange elements from 0 to 19
print("\n Array is:\n ",a)

print("\n a[-8:17:1]  = ",a[-8:17:1]) # a[start:stop:step]
 
# The : operator means all elements till the end.
print("\n a[10:]  = ",a[10:])


 Array is:
  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

 a[-8:17:1]  =  [12 13 14 15 16]

 a[10:]  =  [10 11 12 13 14 15 16 17 18 19]


In [12]:
#ERROR
#Slicing
# A 3-Dimensional array
import numpy as np
a = np.array([[0, 1, 2, 3, 4, 5]
              [6, 7, 8, 9, 10, 11]
              [12, 13, 14, 15, 16, 17]
              [18, 19, 20, 21, 22, 23]
              [24, 25, 26, 27, 28, 29]
              [30, 31, 32, 33, 34, 35]]
print("\n Array is:\n ",a)
 
# slicing and indexing
print("\n a[0, 3:5]  = ",a[0, 3:5]) 
 
print("\n a[4:, 4:]  = ",a[4:, 4:]) 
 
print("\n a[:, 2]  = ",a[:, 2]) 
 
print("\n a[2:;2, ::2]  = ",a[2:;2, ::2]) 

SyntaxError: invalid syntax (<ipython-input-12-848ec53599a6>, line 11)

In [18]:
#Advanced Indexing and slicing
#purely integer indexing
import numpy as np
 
#Here,Index of elements are (0,0),(1,0),(2,1) and the corresponding
#elemensts are selected
#1
a = np.array([[1 ,2 ],[3 ,4 ],[5 ,6 ]])
print(a[[0 ,1 ,2 ],[0 ,0 ,1]])

#2
b = np.array([[0 ,1 ,2],[3 ,4 ,5 ],
              [6 ,7 ,8],[9 ,10 ,11]])
 
print(b[2:3,0:3 ]) #1st slect tuple,2nd slect range from that tuple
print(b[1:3 ,[1,2]])

[1 3 6]
[[6 7 8]]
[[4 5]
 [7 8]]


In [19]:
#Boolean array indexing
import numpy as np
#1
print("#1")
a = np.array([10, 40, 80, 50, 100])
print(a[a>50]) #to select no greater than 50

print("#2")
a = np.array([10, 40, 80, 50, 100])
print(a[a%40==0]**2) #square multiples of 40

print("#3")
b = np.array([[5, 5],[4, 5],[16, 4]])
sumrow = b.sum(-1)
print(b[sumrow%10==0])


#1
[ 80 100]
#2
[1600 6400]
#3
[[ 5  5]
 [16  4]]


In [20]:
#iterating over array
#particular order
import numpy as geek 

a = geek.arange(12) 
print('Original array is:',a) 
print()  
a = a.reshape(3,4) # shape array with 3 rows and 4 columns
print('New array is:',a) 
print()  
 
print('Modified array in C-style order:')
for x in geek.nditer(a, order = 'C'): # iterating an array in a given order
    print(x)
print()

print('Modified array in F-style order:')  
for x in geek.nditer(a, order = 'F'): 
    print(x)

Original array is: [ 0  1  2  3  4  5  6  7  8  9 10 11]

New array is: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Modified array in C-style order:
0
1
2
3
4
5
6
7
8
9
10
11

Modified array in F-style order:
0
4
8
1
5
9
2
6
10
3
7
11
