In [1]:
#Indexing using numpy
import numpy as np
#1
a=np.arange(10,1,-2)
print("\n A sequential array with a negative step: \n",a)
 
# Indexes are specified inside the np.array method.
newarr = a[np.array([3, 1, 2 ])]
print("\n Elements at these indices are:\n",newarr)

#2
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = x[np.array([1, 3, -3])] # Index values can be negative.
print("\n Elements are : \n",arr)


 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]

 Elements are : 
 [2 4 7]


In [3]:
#Slicing a slice object is of the form start:stop:step
import numpy as np
 
a = np.arange(20) # Arrange elements from 0 to 19
print("\n Array is:\n ",a)

print("\n a[-8:17:1]  = ",a[-8:17:1]) # a[start:stop:step]
 
# The : operator means all elements till the end.
print("\n a[10:]  = ",a[10:])


 Array is:
  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

 a[-8:17:1]  =  [12 13 14 15 16]

 a[10:]  =  [10 11 12 13 14 15 16 17 18 19]


In [4]:
#ERROR
#Slicing
# A 3-Dimensional array
import numpy as np
a = np.array([[0, 1, 2, 3, 4, 5]
              [6, 7, 8, 9, 10, 11]
              [12, 13, 14, 15, 16, 17]
              [18, 19, 20, 21, 22, 23]
              [24, 25, 26, 27, 28, 29]
              [30, 31, 32, 33, 34, 35]]
print("\n Array is:\n ",a)
 
# slicing and indexing
print("\n a[0, 3:5]  = ",a[0, 3:5]) 
 
print("\n a[4:, 4:]  = ",a[4:, 4:]) 
 
print("\n a[:, 2]  = ",a[:, 2]) 
 
print("\n a[2:;2, ::2]  = ",a[2:;2, ::2]) 

SyntaxError: invalid syntax (<ipython-input-4-ab51d90ffa51>, line 11)

In [5]:
#Advanced Indexing and slicing
#purely integer indexing
import numpy as np
 
#Here,Index of elements are (0,0),(1,0),(2,1) and the corresponding
#elemensts are selected
#1
a = np.array([[1 ,2 ],[3 ,4 ],[5 ,6 ]])
print(a[[0 ,1 ,2 ],[0 ,0 ,1]])

#2
b = np.array([[0 ,1 ,2],[3 ,4 ,5 ],
              [6 ,7 ,8],[9 ,10 ,11]])
 
print(b[2:3,0:3 ]) #1st slect tuple,2nd slect range from that tuple
print(b[1:3 ,[1,2]])

[1 3 6]
[[6 7 8]]
[[4 5]
 [7 8]]


In [6]:
#Boolean array indexing
import numpy as np
#1
print("#1")
a = np.array([10, 40, 80, 50, 100])
print(a[a>50]) #to select no greater than 50

print("#2")
a = np.array([10, 40, 80, 50, 100])
print(a[a%40==0]**2) #square multiples of 40

print("#3")
b = np.array([[5, 5],[4, 5],[16, 4]])
sumrow = b.sum(-1)
print(b[sumrow%10==0])


#1
[ 80 100]
#2
[1600 6400]
#3
[[ 5  5]
 [16  4]]


In [7]:
#iterating over array
#particular order
import numpy as geek 

a = geek.arange(12) 
print('Original array is:',a) 
print()  
a = a.reshape(3,4) # shape array with 3 rows and 4 columns
print('New array is:',a) 
print()  
 
print('Modified array in C-style order:')
for x in geek.nditer(a, order = 'C'): # iterating an array in a given order
    print(x)
print()

print('Modified array in F-style order:')  
for x in geek.nditer(a, order = 'F'): 
    print(x)

Original array is: [ 0  1  2  3  4  5  6  7  8  9 10 11]

New array is: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Modified array in C-style order:
0
1
2
3
4
5
6
7
8
9
10
11

Modified array in F-style order:
0
4
8
1
5
9
2
6
10
3
7
11
