In [17]:
#1 Creation of arrays
import numpy as np

arr=np.array([1,2,3])
print("Array with rank 1: \n",arr)

#n-dimensional array
arr=np.array([[1,2,3],
              [4,5,6]])
print("Array with rank 2: \n",arr)
print("Array is of type: ", type(arr))
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)
print("Array stores elements of type: ", arr.dtype)

#Constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex') #{(m*n), value, datatype}
print ("\nAn array initialized with all 6s."
            "Array type is complex:\n", d)

#using tuple
arr=np.array((1,2,3))
print("Array created using tuple: \n",arr)


Array with rank 1: 
 [1 2 3]
Array with rank 2: 
 [[1 2 3]
 [4 5 6]]
Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32

An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]
Array created using tuple: 
 [1 2 3]


In [8]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
print("Initial Array: \n",arr)
sliced_arr=arr[:2, ::2]
print("Array with first 2 rows and alternate columns(0 and 2): \n",sliced_arr)
index_arr=arr[[1,1,0,2],
             [2,3,1,0]]
#doubt on this topic
print ("\nElements at indices (1, 3), " "(1, 2), (0, 1), (3, 0):\n", index_arr)

Initial Array: 
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
Array with first 2 rows and alternate columns(0 and 2): 
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [6.  0.  2.  2.6]


In [20]:
#mathematical operations
print ("Adding 1 to every element:", arr + 1)
print ("\nSum of all array elements: ", arr.sum())
print ("\nArray sum:\n", arr + arr) #binary operation

# boolean array indexing example
cond = arr > 0 # cond is a boolean array
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)

# maximum element of array
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",arr.max(axis = 1))
 
# minimum element of array
print ("Column-wise minimum elements:",arr.min(axis = 0))
 
# cumulative sum along each row
print ("Cumulative sum along each row:\n",arr.cumsum(axis = 1))

Adding 1 to every element: [2 3 4]

Sum of all array elements:  6

Array sum:
 [2 4 6]

Elements greater than 0:
 [1 2 3]
Largest element is: 3


AxisError: axis 1 is out of bounds for array of dimension 1

In [11]:
#Constructing Datatype
x = np.array([1, 2])  
print("Integer Datatype: ")
print(x.dtype)   # guessed by Numpy      
x = np.array([1.0, 2.0]) 
print("\nFloat Datatype: ")
print(x.dtype)  # guessed by Numpy
 
# Forced Datatype
x = np.array([1, 2], dtype = np.int64)   
print("\nForcing a Datatype: ")
print(x.dtype)

Integer Datatype: 
int32

Float Datatype: 
float64

Forcing a Datatype: 
int64


In [21]:
# Python program to demonstrate 
# the use of data type object
# with structured array.
import numpy as np
 
dt = np.dtype([('name', np.unicode_, 16),
               ('grades', np.float64, (2,))])
 
# x is a structured array with names
# and marks of students.
# Data type of name of the student is 
# np.unicode_ and data type of marks is 
# np.float(64)
x = np.array([('Sarah', (8.0, 7.0)),
              ('John', (6.0, 7.0))], dtype=dt)
 
print(x[1])
 
print("Grades of John are: ", x[1]['grades'])
print("Names are: ", x['name'])


('John', [6., 7.])
Grades of John are:  [6. 7.]
Names are:  ['Sarah' 'John']


In [4]:
#Indexing using numpy
import numpy as np
#1
a=np.arange(10,1,-2)
print("\n A sequential array with a negative step: \n",a)
 
# Indexes are specified inside the np.array method.
newarr = a[np.array([3, 1, 2 ])]
print("\n Elements at these indices are:\n",newarr)

#2
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = x[np.array([1, 3, -3])] # Index values can be negative.
print("\n Elements are : \n",arr)


 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]

 Elements are : 
 [2 4 7]


In [8]:
#Slicing a slice object is of the form start:stop:step
import numpy as np
 
a = np.arange(20) # Arrange elements from 0 to 19
print("\n Array is:\n ",a)

print("\n a[-8:17:1]  = ",a[-8:17:1]) # a[start:stop:step]
 
# The : operator means all elements till the end.
print("\n a[10:]  = ",a[10:])


 Array is:
  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

 a[-8:17:1]  =  [12 13 14 15 16]

 a[10:]  =  [10 11 12 13 14 15 16 17 18 19]


In [62]:
#ERROR
#Slicing
# A 3-Dimensional array
import numpy as np
a = np.array([[0, 1, 2, 3, 4, 5]
              [6, 7, 8, 9, 10, 11]
              [12, 13, 14, 15, 16, 17]
              [18, 19, 20, 21, 22, 23]
              [24, 25, 26, 27, 28, 29]
              [30, 31, 32, 33, 34, 35]]
print("\n Array is:\n ",a)
 
# slicing and indexing
print("\n a[0, 3:5]  = ",a[0, 3:5]) 
 
print("\n a[4:, 4:]  = ",a[4:, 4:]) 
 
print("\n a[:, 2]  = ",a[:, 2]) 
 
print("\n a[2:;2, ::2]  = ",a[2:;2, ::2]) 

SyntaxError: invalid syntax (<ipython-input-62-3514e312e483>, line 14)

In [18]:
#Advanced Indexing and slicing
#purely integer indexing
import numpy as np
 
#Here,Index of elements are (0,0),(1,0),(2,1) and the corresponding
#elemensts are selected
#1
a = np.array([[1 ,2 ],[3 ,4 ],[5 ,6 ]])
print(a[[0 ,1 ,2 ],[0 ,0 ,1]])

#2
b = np.array([[0 ,1 ,2],[3 ,4 ,5 ],
              [6 ,7 ,8],[9 ,10 ,11]])
 
print(b[2:3,0:3 ]) #1st slect tuple,2nd slect range from that tuple
print(b[1:3 ,[1,2]])

[1 3 6]
[[6 7 8]]
[[4 5]
 [7 8]]


In [19]:
#Boolean array indexing
import numpy as np
#1
print("#1")
a = np.array([10, 40, 80, 50, 100])
print(a[a>50]) #to select no greater than 50

print("#2")
a = np.array([10, 40, 80, 50, 100])
print(a[a%40==0]**2) #square multiples of 40

print("#3")
b = np.array([[5, 5],[4, 5],[16, 4]])
sumrow = b.sum(-1)
print(b[sumrow%10==0])


#1
[ 80 100]
#2
[1600 6400]
#3
[[ 5  5]
 [16  4]]


In [20]:
#iterating over array
#particular order
import numpy as geek 

a = geek.arange(12) 
print('Original array is:',a) 
print()  
a = a.reshape(3,4) # shape array with 3 rows and 4 columns
print('New array is:',a) 
print()  
 
print('Modified array in C-style order:')
for x in geek.nditer(a, order = 'C'): # iterating an array in a given order
    print(x)
print()

print('Modified array in F-style order:')  
for x in geek.nditer(a, order = 'F'): 
    print(x)

Original array is: [ 0  1  2  3  4  5  6  7  8  9 10 11]

New array is: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Modified array in C-style order:
0
1
2
3
4
5
6
7
8
9
10
11

Modified array in F-style order:
0
4
8
1
5
9
2
6
10
3
7
11


In [22]:
#Numpy Binary operations
# bitwise_and() function
#or, xor same
import numpy as np
in_num1 = 10
in_num2 = 11
in_arr1 = [2, 8, 125]
in_arr2 = [3, 3, 115]
#for num 
print ("Input  number1 : ", in_num1)
print ("Input  number2 : ", in_num2)    
out_num = np.bitwise_and(in_num1, in_num2) #bitwise and operation
print ("bitwise_and of 10 and 11 : ", out_num)
#for array
print ("Input array1 : ", in_arr1) 
print ("Input array2 : ", in_arr2)
out_arr = geek.bitwise_and(in_arr1, in_arr2) 
print ("Output array after bitwise_and: ", out_arr)

Input  number1 :  10
Input  number2 :  11
bitwise_and of 10 and 11 :  10
Input array1 :  [2, 8, 125]
Input array2 :  [3, 3, 115]
Output array after bitwise_and:  [  2   0 113]


In [24]:
#Numpy Binary operations
#invert() function
#numpy.left_shift() #same for right shift
import numpy as np
#same for num and array

in_arr = [2, 0, 25]
bit_shift =[3, 4, 5]
print ("Input array : ", in_arr)  
out_arr = np.invert(in_arr) #invert function
print ("Output array after inversion: ", out_arr)

out_arr = np.left_shift(in_arr, bit_shift) #left shift fuction
print ("Output array after left shifting: ", out_arr) 


Input array :  [2, 0, 25]
Output array after inversion:  [ -3  -1 -26]
Output array after left shifting:  [ 16   0 800]


In [26]:
#Numpy Binary operations
#binary form of input no, for -ve no if width is not given than
#a minus sign is added to front #if width is given than 
#2's complement of no is returned
import numpy as geek
 
in_arr = [5, -8 ]  
print ("Input array : ", in_arr) 
 
# binary representation of first array  
# element without using width parameter
out_num = geek.binary_repr(in_arr[0])
print("Binary representation of 5")
print ("Without using width parameter : ", out_num) 
 
# binary representation of first array
# element using width parameter
out_num = geek.binary_repr(in_arr[0], width = 5)
print ("Using width parameter: ", out_num) 
print("\nBinary representation of -8")
 
# binary representation of 2nd array
# element without using width parameter
out_num = geek.binary_repr(in_arr[1])
print ("Without using width parameter : ", out_num) 
 
# binary representation of 2nd array
# element  using width parameter
out_num = geek.binary_repr(in_arr[1], width = 5)
print ("Using width parameter : ", out_num) 

Input array :  [5, -8]
Binary representation of 5
Without using width parameter :  101
Using width parameter:  00101

Binary representation of -8
Without using width parameter :  -1000
Using width parameter :  11000


In [ ]:
#Pending for doubts
#numpy.packbits(myarray, axis=None) 
#numpy.unpackbits(myarray, axis=None) :

In [38]:
#Trignometric operations

#sin() func
import numpy as np
import math
 
in_array = [0, math.pi / 2, np.pi / 3, np.pi]
print ("Input array : \n", in_array) 
Sin_Values = np.sin(in_array)
print ("\nSine values : \n", Sin_Values)
cos_Values = np.cos(in_array)
print ("\nCosine values : \n", cos_Values)

#tan()-compute tangent element wise
#arcsin()-Inverse sine/cosine/tangent, element wise
#arctan2()-Element wise arc tanget of x1/x2
#choosing the quadrant correctly
#degrees()- Convert angles from radians to degrees
#rad2deg()-Convert angles from rwd to deg or vice-versa
#radians()-convert angles from degreee to radians
#hypot()-Given 'legs'of a right triangle. return its hypotenuse
#unwrap()-Unwrap by changing deltas btwn vlues to 2*pi compliment
print(np.hypot(3,4))

Input array : 
 [0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]

Sine values : 
 [0.00000000e+00 1.00000000e+00 8.66025404e-01 1.22464680e-16]

Cosine values : 
 [ 1.000000e+00  6.123234e-17  5.000000e-01 -1.000000e+00]
5.0


In [39]:
#Hyperbolic functions

import numpy as np
import math
#cosh()
#same for sinh,tanh,arcsinh,arccosh,arctanh

in_array = [0, math.pi / 2, np.pi / 3, np.pi]
print ("Input array : \n", in_array)
cosh_Values = np.cosh(in_array)
print ("\ncosine Hyperbolic values : \n", cosh_Values)


Input array : 
 [0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]

cosine Hyperbolic values : 
 [ 1.          2.50917848  1.60028686 11.59195328]


In [46]:
#function for rounding

#1 numpy.around(arr, decimals = 0, out = None) 
#to evenly round array elements to the given number of decimals
in_array = [.53, 1.54, .71]
print ("\nInput array : \n", in_array)
round_off_values = np.around(in_array)
print ("\nRounded values : \n", round_off_values)
 
in_array = [.5538, 1.33354, .71445]
print ("\nInput array : \n", in_array)
round_off_values = np.around(in_array, decimals = 3)
print ("\nRounded values : \n", round_off_values)

#2 numpy.round_(arr, decimals = 0, out = None) 
#round an array to the given number of decimals.
in_array = [.53, 1.54, .71]
print ("\nInput array : \n", in_array)
round_off_values = np.round_(in_array)
print ("\nRounded values : \n", round_off_values)
 
in_array = [.5538, 1.33354, .71445]
print ("\nInput array : \n", in_array)
round_off_values = np.round_(in_array, decimals = 3)
print ("\nRounded values : \n", round_off_values)

#rint()-round to nearest integers towards zero
#fix()-round to nearset
print(np.fix(5.6))
#floor()-return floor of input,elemnt wise
#ciel()-return ceiling of input,element wise'
#trunc()-return truncated value of input,elemnt wise


Input array : 
 [0.53, 1.54, 0.71]

Rounded values : 
 [1. 2. 1.]

Input array : 
 [0.5538, 1.33354, 0.71445]

Rounded values : 
 [0.554 1.334 0.714]

Input array : 
 [0.53, 1.54, 0.71]

Rounded values : 
 [1. 2. 1.]

Input array : 
 [0.5538, 1.33354, 0.71445]

Rounded values : 
 [0.554 1.334 0.714]
5.0


In [49]:
#Exponenets and logarthimic functions
import numpy as np
#exponential
in_array = [1, 3, 5]
print ("Input array : ", in_array)
out_array = np.exp(in_array)
print ("Output array : ", out_array)
print("\n")

#Natural logarithm of x 
in_array = [1, 3, 5, 2**8]

print ("Input array : ", in_array) 
out_array = np.log(in_array)
print ("Output array : ", out_array)
print("np.log(4**4) : ", np.log(4**4))
print("np.log(2**8) : ", np.log(2**8))

Input array :  [1, 3, 5]
Output array :  [  2.71828183  20.08553692 148.4131591 ]


Input array :  [1, 3, 5, 256]
Output array :  [0.         1.09861229 1.60943791 5.54517744]
np.log(4**4) :  5.545177444479562
np.log(2**8) :  5.545177444479562


In [55]:
#Airthmetic Functions
#1 Reciprocal
in_num=2.0
out_num=np.reciprocal(in_num)
print("Reciprocal is : ",out_num)

#2 divide
arr1=[2,27,2,21,23]
arr2=[2,3,4,5,6]
out=np.divide(arr1,arr2)
print("Output array is : \n",out)


#add,positive,neagtive,multiply,power,subtract
#true_divide,floor_divide,float_power(first elmt raised to power from second array,element wise)
#mod,remainder,divmod(quotient&remainder)

Reciprocal is :  0.5
Output array is : 
 [1.         9.         0.5        4.2        3.83333333]


In [59]:
#Complex number function
#1 isreal() test elemst wise,return result as boolean array
print("Is real :",np.isreal([1+1j,0j]),"\n")
print("Is Real",np.isreal([1,0]))

#2 conj() - to conjugate any complex number
in_num=2+4j
out_num=np.conj(in_num)
print("Output conjugated part is : ",out_num)

Is real : [False  True] 

Is Real [ True  True]
Output conjugated part is :  (2-4j)


In [63]:
#Special Functions
#1 cbrt() - calculate cube root of x
arr1=[1,27000,64,-1000]
print("cbrt values are: ",np.cbrt(arr1))

#2 clip() - used to limit the value in array
in_array = [1, 2, 3, 4, 5, 6, 7, 8 ]
print ("\nInput array : ", in_array) 
out_array = np.clip(in_array, a_min = 2, a_max = 6)
print ("Output array : ", out_array)

cbrt values are:  [  1.  30.   4. -10.]

Input array :  [1, 2, 3, 4, 5, 6, 7, 8]
Output array :  [2 2 3 4 5 6 6 6]
