In [1]:
#Trignometric operations

#sin() func
import numpy as np
import math
 
in_array = [0, math.pi / 2, np.pi / 3, np.pi]
print ("Input array : \n", in_array) 
Sin_Values = np.sin(in_array)
print ("\nSine values : \n", Sin_Values)
cos_Values = np.cos(in_array)
print ("\nCosine values : \n", cos_Values)

#tan()-compute tangent element wise
#arcsin()-Inverse sine/cosine/tangent, element wise
#arctan2()-Element wise arc tanget of x1/x2
#choosing the quadrant correctly
#degrees()- Convert angles from radians to degrees
#rad2deg()-Convert angles from rwd to deg or vice-versa
#radians()-convert angles from degreee to radians
#hypot()-Given 'legs'of a right triangle. return its hypotenuse
#unwrap()-Unwrap by changing deltas btwn vlues to 2*pi compliment
print(np.hypot(3,4))

Input array : 
 [0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]

Sine values : 
 [0.00000000e+00 1.00000000e+00 8.66025404e-01 1.22464680e-16]

Cosine values : 
 [ 1.000000e+00  6.123234e-17  5.000000e-01 -1.000000e+00]
5.0


In [2]:
#Hyperbolic functions

import numpy as np
import math
#cosh()
#same for sinh,tanh,arcsinh,arccosh,arctanh

in_array = [0, math.pi / 2, np.pi / 3, np.pi]
print ("Input array : \n", in_array)
cosh_Values = np.cosh(in_array)
print ("\ncosine Hyperbolic values : \n", cosh_Values)

Input array : 
 [0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]

cosine Hyperbolic values : 
 [ 1.          2.50917848  1.60028686 11.59195328]


In [4]:
#function for rounding

#1 numpy.around(arr, decimals = 0, out = None) 
#to evenly round array elements to the given number of decimals
in_array = [.53, 1.54, .71]
print ("\nInput array : \n", in_array)
round_off_values = np.around(in_array)
print ("\nRounded values : \n", round_off_values)
 
in_array = [.5538, 1.33354, .71445]
print ("\nInput array : \n", in_array)
round_off_values = np.around(in_array, decimals = 3)
print ("\nRounded values : \n", round_off_values)

#2 numpy.round_(arr, decimals = 0, out = None) 
#round an array to the given number of decimals.
in_array = [.53, 1.54, .71]
print ("\nInput array : \n", in_array)
round_off_values = np.round_(in_array)
print ("\nRounded values : \n", round_off_values)
 
in_array = [.5538, 1.33354, .71445]
print ("\nInput array : \n", in_array)
round_off_values = np.round_(in_array, decimals = 3)
print ("\nRounded values : \n", round_off_values)

#rint()-round to nearest integers towards zero
#fix()-round to nearset
print(np.fix(5.6))
#floor()-return floor of input,elemnt wise
#ciel()-return ceiling of input,element wise'
#trunc()-return truncated value of input,elemnt wise


Input array : 
 [0.53, 1.54, 0.71]

Rounded values : 
 [1. 2. 1.]

Input array : 
 [0.5538, 1.33354, 0.71445]

Rounded values : 
 [0.554 1.334 0.714]

Input array : 
 [0.53, 1.54, 0.71]

Rounded values : 
 [1. 2. 1.]

Input array : 
 [0.5538, 1.33354, 0.71445]

Rounded values : 
 [0.554 1.334 0.714]
5.0


In [5]:
#Exponenets and logarthimic functions
import numpy as np
#exponential
in_array = [1, 3, 5]
print ("Input array : ", in_array)
out_array = np.exp(in_array)
print ("Output array : ", out_array)
print("\n")

#Natural logarithm of x 
in_array = [1, 3, 5, 2**8]

print ("Input array : ", in_array) 
out_array = np.log(in_array)
print ("Output array : ", out_array)
print("np.log(4**4) : ", np.log(4**4))
print("np.log(2**8) : ", np.log(2**8))

Input array :  [1, 3, 5]
Output array :  [  2.71828183  20.08553692 148.4131591 ]


Input array :  [1, 3, 5, 256]
Output array :  [0.         1.09861229 1.60943791 5.54517744]
np.log(4**4) :  5.545177444479562
np.log(2**8) :  5.545177444479562


In [6]:
#Airthmetic Functions
#1 Reciprocal
in_num=2.0
out_num=np.reciprocal(in_num)
print("Reciprocal is : ",out_num)

#2 divide
arr1=[2,27,2,21,23]
arr2=[2,3,4,5,6]
out=np.divide(arr1,arr2)
print("Output array is : \n",out)


#add,positive,neagtive,multiply,power,subtract
#true_divide,floor_divide,float_power(first elmt raised to power from second array,element wise)
#mod,remainder,divmod(quotient&remainder)

Reciprocal is :  0.5
Output array is : 
 [1.         9.         0.5        4.2        3.83333333]


In [7]:
#Complex number function
#1 isreal() test elemst wise,return result as boolean array
print("Is real :",np.isreal([1+1j,0j]),"\n")
print("Is Real",np.isreal([1,0]))

#2 conj() - to conjugate any complex number
in_num=2+4j
out_num=np.conj(in_num)
print("Output conjugated part is : ",out_num)

Is real : [False  True] 

Is Real [ True  True]
Output conjugated part is :  (2-4j)


In [8]:
#Special Functions
#1 cbrt() - calculate cube root of x
arr1=[1,27000,64,-1000]
print("cbrt values are: ",np.cbrt(arr1))

#2 clip() - used to limit the value in array
in_array = [1, 2, 3, 4, 5, 6, 7, 8 ]
print ("\nInput array : ", in_array) 
out_array = np.clip(in_array, a_min = 2, a_max = 6)
print ("Output array : ", out_array)

cbrt values are:  [  1.  30.   4. -10.]

Input array :  [1, 2, 3, 4, 5, 6, 7, 8]
Output array :  [2 2 3 4 5 6 6 6]
